spring:
  security:
    oauth2:
      client:
        registration: 
          google: 
            client-id: 489628837861-ttr8bjl9ptu0br8oqnip94gg7fvgqp0f.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile